### ISSUE TITLE
Fix: Search

### ISSUE THREAD

**Issue by sdeblebo** [standrewsdigital/wp-news-media#16]
Search for news from main search box at top of page, or from search box in middle of home page doesn't work.

**Comment by bambattajb** [comment]
When a user uses the Archive Search field it moves them to the Archive page where it will display listings based on their search. Does the archive search (in the News Room) also need to display the tags underneath when the user types?

![screenshot from 2018-05-25 10-28-03](https://user-images.githubusercontent.com/480898/40537242-577bb824-6006-11e8-90fd-451e0642bb5f.png)

![screenshot from 2018-05-25 10-28-11](https://user-images.githubusercontent.com/480898/40537250-5c24b1a0-6006-11e8-838a-cb151ab05133.png)
