### ISSUE TITLE
Fix - use checkboxes when assigning languages to experts.

### ISSUE THREAD

**Issue by sdeblebo** [standrewsdigital/wp-news-media#33]
Please can you use checkboxes to allow more than one language to be assigned to an expert. It currently shows a radio button.

**Comment by bambattajb** [comment]
I've just fixed this and https://github.com/standrewsdigital/wp-news-media/issues/32
It is obviously live but the changes will be pushed in my next commit.

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)
