### ISSUE TITLE
FIX - secondary navigation not appearing under 'Experts' or 'Videos'

### ISSUE THREAD

**Issue by woodenbridge94** [standrewsdigital/wp-news-media#39]
You can see if you navigate to '/media-centre/expert-guide-directory/' that the light blue secondary navigation is visible, but when clicking on a specific Expert this disappears.
After trying to solve this myself I think this is to do with where the Experts and Videos are sitting and who their parent is.

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by woodenbridge94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - sub nav is missing for media centre when on an expert page](https://trello.com/c/4C5QyW3b/261-fix-sub-nav-is-missing-for-media-centre-when-on-an-expert-page)

**Comment by sdeblebo** [comment]
Fixed by changing permalinks using plugin 'Permalink Manager Lite'
