### ISSUE TITLE
Fix : Add Breadcrumbs

### ISSUE THREAD

**Issue by bambattajb** [standrewsdigital/wp-news-media#4]
Breadcrumbs should appear under 2nd and 3rd within the Media centre

**Comment by sdeblebo** [comment]
Can you please add breadcrumbs when looking at an individual expert so it shows e.g.

Home > Media centre > Experts guide directory > Charlie Bird.

**Comment by bambattajb** [comment]
Thanks for spotting that. I will prioritise the issue.
