### ISSUE TITLE
Fix : ExpertFilter | Can't search by tags, only on people's names

### ISSUE THREAD

**Issue by bambattajb** [standrewsdigital/wp-news-media#7]
**Searches through tags and expert names to display experts**

**Comment by bambattajb** [comment]
Tags are now included as a searchable element of the person cards

![screenshot from 2018-05-24 14-07-07](https://user-images.githubusercontent.com/480898/40487346-cc847418-5f5b-11e8-85d5-d9f6e7d1fd27.png)

**Comment by sdeblebo** [comment]
We have found an issue where the news team have given us a list of specialisms that are more comprehensive than the tags. Would it be possible to search against the content in their profile as well as the content on their card?

**Comment by sdeblebo** [comment]
We also have a design issue where the content is not fitting onto our contact card pattern. We will need to discuss this with the news team today (Wednesday 30 May) to see what they want to do.

**Comment by drk4** [comment]
When you submit the form it currently navigates away to the archive search results.
I think submit form action should be limited to searching the experts and remaining on this page.

**Comment by sdeblebo** [comment]
I have fixed the search via tags.
